services:
  fpm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    container_name: nsign_php_fpm
    user: "${USER}"
    volumes:
      - ../:/opt/app
    networks:
      - nsign-network

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: nginx
    container_name: nsign_nginx
    environment:
      - NGINX_SERVER_PORT=8080
      - API_FPM_HOST=fpm
    ports:
      - 9095:8080
    depends_on:
      - fpm
    networks:
      - nsign-network

networks:
  nsign-network: